[package]
name = "vsr-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.213", features = ["serde_derive"] }
serde_json = "1.0.132"
thiserror = "1.0.65"
tokio = { version = "1.41.0", features = ["full"] }
